from django.urls import path

from . import views

app_name = "employees"

urlpatterns = [
    path("", views.employee_login, name="login"),
    path("register/", views.employee_register, name="register"),
    path("select-role/", views.select_login_role, name="select_login_role"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path(
        "workspace/it_support/curriculum-management/learning-management/class-management/<slug:tool>/",
        views.it_support_class_page,
        name="it_support_class_page",
    ),
    path(
        "workspace/it_support/curriculum-management/learning-management/timetable-management/timetable-generation/manual-allocation/",
        views.learning_manual_teacher_allocation,
        name="learning_manual_teacher_allocation",
    ),
    path(
        "workspace/it_support/curriculum-management/learning-management/timetable-management/<slug:tool>/",
        views.it_support_timetable_page,
        name="it_support_timetable_page",
    ),
    path(
        "workspace/it_support/curriculum-management/learning-management/<slug:page>/",
        views.it_support_learning_page,
        name="it_support_learning_page",
    ),
    path(
        "workspace/it_support/curriculum-management/exam-management/exam-timetable-generation/manual-allocation/",
        views.exam_manual_supervisor_allocation,
        name="exam_manual_supervisor_allocation",
    ),
    path(
        "workspace/it_support/curriculum-management/exam-management/exam-records/<int:exam_id>/levels/<int:level_id>/",
        views.exam_record_detail,
        name="exam_record_level",
    ),
    path(
        "workspace/it_support/curriculum-management/exam-management/exam-records/<int:exam_id>/update/",
        views.update_exam_record,
        name="update_exam_record",
    ),
    path(
        "workspace/it_support/curriculum-management/exam-management/exam-records/<int:exam_id>/delete/",
        views.delete_exam_record,
        name="delete_exam_record",
    ),
    path(
        "workspace/it_support/curriculum-management/exam-management/exam-records/<int:exam_id>/",
        views.exam_record_detail,
        name="exam_record_detail",
    ),
    path(
        "workspace/it_support/curriculum-management/exam-management/<slug:tool>/",
        views.it_support_exam_page,
        name="it_support_exam_page",
    ),
    path(
        "workspace/it_support/curriculum-management/e-learning-management/<slug:page>/",
        views.it_support_elearning_page,
        name="it_support_elearning_page",
    ),
    path(
        "workspace/it_support/curriculum-management/<slug:section>/",
        views.it_support_curriculum_section,
        name="it_support_curriculum_section",
    ),
    path(
        "workspace/it_support/human-resource-management/employee-management/",
        views.it_support_employee_management,
        name="it_support_employee_management",
    ),
    path(
        "workspace/it_support/human-resource-management/employee-management/<int:employee_id>/update/",
        views.update_workspace_employee,
        name="update_workspace_employee",
    ),
    path(
        "workspace/it_support/human-resource-management/employee-management/<int:employee_id>/toggle-status/",
        views.toggle_workspace_employee_status,
        name="toggle_workspace_employee_status",
    ),
    path(
        "workspace/it_support/human-resource-management/employee-management/<int:employee_id>/delete/",
        views.delete_workspace_employee,
        name="delete_workspace_employee",
    ),
    path(
        "workspace/it_support/student-management/<int:student_id>/profile/",
        views.workspace_student_profile_legacy,
        name="workspace_student_profile_legacy",
    ),
    path(
        "workspace/it_support/student-management/<int:student_id>/update/",
        views.update_workspace_student,
        name="update_workspace_student",
    ),
    path(
        "workspace/it_support/student-management/<int:student_id>/toggle-status/",
        views.toggle_workspace_student_status,
        name="toggle_workspace_student_status",
    ),
    path(
        "workspace/it_support/student-management/<int:student_id>/delete/",
        views.delete_workspace_student,
        name="delete_workspace_student",
    ),
    path(
        "workspace/it_support/reports/curriculum-reports/exam-reports/students/",
        views.it_support_exam_report_students,
        name="it_support_exam_report_students",
    ),
    path(
        "workspace/it_support/reports/curriculum-reports/<slug:page>/",
        views.it_support_curriculum_report_page,
        name="it_support_curriculum_report_page",
    ),
    path(
        "workspace/it_support/reports/<slug:section>/",
        views.it_support_report_section,
        name="it_support_report_section",
    ),
    path(
        "workspace/it_support/<slug:module>/",
        views.it_support_module,
        name="it_support_module",
    ),
    path(
        "workspace/teacher/exam-records/<int:exam_id>/classes/<int:class_id>/",
        views.teacher_exam_record_detail,
        name="teacher_exam_record_class",
    ),
    path(
        "workspace/teacher/exam-records/<int:exam_id>/analytics/classes/<int:class_id>/",
        views.teacher_exam_analytics,
        name="teacher_exam_analytics_class",
    ),
    path(
        "workspace/teacher/exam-records/<int:exam_id>/analytics/all/",
        views.teacher_exam_analytics,
        {"view_all": True},
        name="teacher_exam_analytics_all",
    ),
    path(
        "workspace/teacher/exam-records/<int:exam_id>/analytics/",
        views.teacher_exam_analytics,
        name="teacher_exam_analytics",
    ),
    path(
        "workspace/teacher/exam-records/<int:exam_id>/",
        views.teacher_exam_record_detail,
        name="teacher_exam_record_detail",
    ),
    path("workspace/teacher/exam-records/", views.teacher_exam_records, name="teacher_exam_records"),
    path(
        "workspace/teacher/subject-attendance/classes/<int:class_id>/subjects/<int:subject_id>/",
        views.teacher_subject_attendance_profile,
        name="teacher_subject_attendance_profile",
    ),
    path(
        "workspace/teacher/subject-attendance/classes/<int:class_id>/",
        views.teacher_subject_attendance_class,
        name="teacher_subject_attendance_class",
    ),
    path(
        "workspace/teacher/subject-attendance/",
        views.teacher_subject_attendance,
        name="teacher_subject_attendance",
    ),
    path(
        "workspace/teacher/learning-reports/",
        views.teacher_learning_reports,
        name="teacher_learning_reports",
    ),
    path(
        "workspace/teacher/my-class/<slug:tool>/",
        views.teacher_my_class_page,
        name="teacher_my_class_page",
    ),
    path("workspace/teacher/my-class/", views.teacher_my_class, name="teacher_my_class"),
    path(
        "workspace/teacher/e-learning/assessments/<int:assessment_id>/classes/<int:class_id>/",
        views.teacher_elearning_assessment_detail,
        name="teacher_elearning_assessment_class",
    ),
    path(
        "workspace/teacher/e-learning/assessments/<int:assessment_id>/",
        views.teacher_elearning_assessment_detail,
        name="teacher_elearning_assessment_detail",
    ),
    path(
        "workspace/teacher/e-learning/learning-materials/<int:material_id>/view/",
        views.teacher_elearning_material_view,
        name="teacher_elearning_material_view",
    ),
    path(
        "workspace/teacher/e-learning/learning-materials/<int:material_id>/download/",
        views.teacher_elearning_material_download,
        name="teacher_elearning_material_download",
    ),
    path(
        "workspace/teacher/e-learning/attendance/levels/<int:level_id>/subjects/<int:subject_id>/",
        views.teacher_elearning_attendance_profile,
        name="teacher_elearning_attendance_profile",
    ),
    path(
        "workspace/teacher/e-learning/attendance/levels/<int:level_id>/",
        views.teacher_elearning_attendance_level,
        name="teacher_elearning_attendance_level",
    ),
    path(
        "workspace/teacher/e-learning/<slug:tool>/",
        views.teacher_elearning_page,
        name="teacher_elearning_page",
    ),
    path("workspace/teacher/e-learning/", views.teacher_elearning, name="teacher_elearning"),
    path("workspace/switch-role/", views.switch_workspace_role, name="switch_workspace_role"),
    path(
        "workspace/switch-role/employees/",
        views.workspace_role_employees,
        name="workspace_role_employees",
    ),
    path(
        "workspace/students/search/",
        views.workspace_student_search,
        name="workspace_student_search",
    ),
    path(
        "workspace/students/<int:student_id>/profile/",
        views.workspace_student_profile,
        name="workspace_student_profile",
    ),
    path("workspace/<slug:role>/", views.role_dashboard, name="role_dashboard"),
    path("settings/", views.system_settings, name="system_settings"),
    path(
        "settings/academic-calendar/",
        views.academic_calendar_settings,
        name="academic_calendar_settings",
    ),
    path(
        "settings/academic-calendar/<int:year_id>/update/",
        views.update_academic_year,
        name="update_academic_year",
    ),
    path(
        "settings/academic-calendar/<int:year_id>/delete/",
        views.delete_academic_year,
        name="delete_academic_year",
    ),
    path(
        "settings/academic-calendar/set-current/",
        views.set_current_academic_calendar,
        name="set_current_academic_calendar",
    ),
    path("settings/school-profile/", views.school_profile_settings, name="school_profile_settings"),
    path(
        "settings/school-profile/contact-location/",
        views.school_profile_contact_location_settings,
        name="school_profile_contact_location_settings",
    ),
    path(
        "settings/school-profile/branding/",
        views.school_profile_branding_settings,
        name="school_profile_branding_settings",
    ),
    path(
        "settings/school-profile/leadership-structure/",
        views.school_profile_leadership_settings,
        name="school_profile_leadership_settings",
    ),
    path(
        "settings/school-profile/academic-setup/",
        views.school_profile_academic_setup_settings,
        name="school_profile_academic_setup_settings",
    ),
    path(
        "settings/school-profile/capacity-operations/",
        views.school_profile_operations_settings,
        name="school_profile_operations_settings",
    ),
    path(
        "settings/school-profile/financial/",
        views.school_profile_financial_settings,
        name="school_profile_financial_settings",
    ),
    path(
        "settings/school-profile/compliance-documents/",
        views.school_profile_compliance_settings,
        name="school_profile_compliance_settings",
    ),
    path("settings/curriculum/", views.curriculum_settings, name="curriculum_settings"),
    path(
        "settings/curriculum/academic-levels/",
        views.academic_levels_settings,
        name="academic_levels_settings",
    ),
    path(
        "settings/curriculum/academic-levels/<int:level_id>/update/",
        views.update_academic_level,
        name="update_academic_level",
    ),
    path(
        "settings/curriculum/academic-levels/<int:level_id>/toggle-status/",
        views.toggle_academic_level_status,
        name="toggle_academic_level_status",
    ),
    path(
        "settings/curriculum/academic-levels/<int:level_id>/delete/",
        views.delete_academic_level,
        name="delete_academic_level",
    ),
    path(
        "settings/curriculum/learning-areas/",
        views.learning_areas_settings,
        name="learning_areas_settings",
    ),
    path(
        "settings/curriculum/learning-timetable/",
        views.learning_timetable_settings,
        name="learning_timetable_settings",
    ),
    path(
        "settings/curriculum/learning-timetable/<int:profile_id>/delete/",
        views.delete_learning_timetable_profile,
        name="delete_learning_timetable_profile",
    ),
    path(
        "settings/curriculum/e-learning-timetable/",
        views.elearning_timetable_settings,
        name="elearning_timetable_settings",
    ),
    path(
        "settings/curriculum/e-learning-timetable/<int:profile_id>/delete/",
        views.delete_elearning_timetable_profile,
        name="delete_elearning_timetable_profile",
    ),
    path(
        "settings/curriculum/exam-settings/",
        views.exam_settings,
        name="exam_settings",
    ),
    path(
        "settings/curriculum/exam-settings/timetable/",
        views.exam_timetable_settings,
        name="exam_timetable_settings",
    ),
    path(
        "settings/curriculum/exam-settings/timetable/<int:profile_id>/delete/",
        views.delete_exam_timetable_profile,
        name="delete_exam_timetable_profile",
    ),
    path(
        "settings/curriculum/exam-settings/<int:level_id>/",
        views.exam_level_settings,
        name="exam_level_settings",
    ),
    path(
        "settings/curriculum/exam-settings/<int:level_id>/marks/",
        views.save_exam_subject_marks,
        name="save_exam_subject_marks",
    ),
    path(
        "settings/curriculum/exam-settings/<int:level_id>/reorder/",
        views.reorder_exam_subjects,
        name="reorder_exam_subjects",
    ),
    path(
        "settings/curriculum/exam-settings/<int:level_id>/combined-subjects/create/",
        views.create_combined_exam_subject,
        name="create_combined_exam_subject",
    ),
    path(
        "settings/curriculum/exam-settings/combined-subjects/<int:combined_id>/delete/",
        views.delete_combined_exam_subject,
        name="delete_combined_exam_subject",
    ),
    path(
        "settings/curriculum/grading-system/",
        views.grading_system_settings,
        name="grading_system_settings",
    ),
    path(
        "settings/curriculum/grading-system/default/",
        views.grading_system_default,
        name="grading_system_default",
    ),
    path(
        "settings/curriculum/grading-system/levels/<int:level_id>/",
        views.grading_level_settings,
        name="grading_level_settings",
    ),
    path(
        "settings/curriculum/grading-system/levels/<int:level_id>/reset/",
        views.reset_level_grading,
        name="reset_level_grading",
    ),
    path(
        "settings/curriculum/grading-system/bands/<int:grade_band_id>/delete/",
        views.delete_grade_band,
        name="delete_grade_band",
    ),
    path(
        "settings/curriculum/learning-areas/<int:area_id>/update/",
        views.update_learning_area,
        name="update_learning_area",
    ),
    path(
        "settings/curriculum/learning-areas/<int:area_id>/toggle-status/",
        views.toggle_learning_area_status,
        name="toggle_learning_area_status",
    ),
    path(
        "settings/curriculum/learning-areas/<int:area_id>/delete/",
        views.delete_learning_area,
        name="delete_learning_area",
    ),
    path("settings/finance/", views.finance_settings, name="finance_settings"),
    path("settings/hr/", views.hr_settings, name="hr_settings"),
    path("profile/photo/", views.update_profile_image, name="update_profile_image"),
    path("logout/", views.employee_logout, name="logout"),
]
