# Generated by Django 6.1 on 2026-08-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='level name')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='level code')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='level order')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'academic level',
                'verbose_name_plural': 'academic levels',
                'ordering': ['order', 'name'],
            },
        ),
    ]
