# Generated by Django 6.1 on 2026-08-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiclevel',
            name='category',
            field=models.CharField(choices=[('PRE_PRIMARY', 'Pre-Primary'), ('LOWER_PRIMARY', 'Lower Primary'), ('UPPER_PRIMARY', 'Upper Primary'), ('JUNIOR_SECONDARY', 'Junior Secondary'), ('SENIOR_SECONDARY', 'Senior Secondary'), ('OTHER', 'Other')], default='OTHER', max_length=30, verbose_name='level category'),
        ),
    ]
