# Generated by Django 6.1 on 2026-08-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_academic_level_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiclevel',
            name='category',
            field=models.CharField(choices=[('PRE_PRIMARY', 'PRE-PRIMARY'), ('LOWER_PRIMARY', 'LOWER PRIMARY'), ('UPPER_PRIMARY', 'UPPER PRIMARY'), ('JUNIOR_SECONDARY', 'JUNIOR SECONDARY'), ('SENIOR_SECONDARY', 'SENIOR SECONDARY'), ('OTHER', 'OTHER')], default='OTHER', max_length=30, verbose_name='level category'),
        ),
        migrations.AlterField(
            model_name='academiclevel',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10),
        ),
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='learning area name')),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_areas', to='curriculum.academiclevel', verbose_name='education level')),
            ],
            options={
                'verbose_name': 'learning area',
                'verbose_name_plural': 'learning areas',
                'ordering': ['display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('education_level', 'code'), name='unique_learning_area_code_per_level')],
            },
        ),
    ]
