# Generated by Django 6.1 on 2026-08-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_exam_subject_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsubjectsetting',
            options={'ordering': ['academic_level__order', 'display_order', 'learning_area__display_order', 'learning_area__name'], 'verbose_name': 'exam subject setting', 'verbose_name_plural': 'exam subject settings'},
        ),
        migrations.AddField(
            model_name='examsubjectsetting',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
