# Generated by Django 6.1 on 2026-08-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_combined_exam_subject_multiple_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubjectsetting',
            name='out_of_marks',
            field=models.PositiveIntegerField(default=100, verbose_name='out of marks'),
        ),
        migrations.AlterField(
            model_name='learningarea',
            name='total_marks',
            field=models.PositiveIntegerField(default=100, verbose_name='total marks'),
        ),
    ]
