# Generated by Django 6.1 on 2026-08-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_remove_marks_decimals'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimetableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'exam timetable session',
                'verbose_name_plural': 'exam timetable sessions',
                'ordering': ['start_time', 'end_time', 'name'],
            },
        ),
    ]
