# Generated by Django 6.1 on 2026-08-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_system_grade_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeband',
            name='end_percent',
            field=models.PositiveIntegerField(verbose_name='end %'),
        ),
        migrations.AlterField(
            model_name='gradeband',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradeband',
            name='start_percent',
            field=models.PositiveIntegerField(verbose_name='start %'),
        ),
    ]
