# Generated by Django 6.1 on 2026-08-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_grade_band_whole_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeband',
            name='description',
        ),
    ]
