# Generated by Django 6.1 on 2026-08-17 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_remove_gradeband_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeband',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_bands', to='curriculum.academiclevel', verbose_name='academic level'),
        ),
        migrations.AlterField(
            model_name='gradeband',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.UniqueConstraint(condition=models.Q(('academic_level__isnull', True)), fields=('code',), name='unique_default_grade_band_code'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.UniqueConstraint(condition=models.Q(('academic_level__isnull', False)), fields=('academic_level', 'code'), name='unique_level_grade_band_code'),
        ),
    ]
