# Generated by Django 6.1 on 2026-08-17 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_gradeband_per_academic_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningScheduleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('study_days', models.JSONField(default=list)),
                ('lesson_duration_minutes', models.PositiveIntegerField(default=40)),
                ('first_class_start_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_levels', models.ManyToManyField(related_name='learning_schedule_profiles', to='curriculum.academiclevel')),
            ],
            options={
                'verbose_name': 'learning schedule profile',
                'verbose_name_plural': 'learning schedule profiles',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningScheduleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='curriculum.learningscheduleprofile')),
            ],
            options={
                'verbose_name': 'learning schedule activity',
                'verbose_name_plural': 'learning schedule activities',
                'ordering': ['start_time', 'order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='learningscheduleprofile',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_learning_schedule_profile_per_category'),
        ),
    ]
