# Generated by Django 6.1 on 2026-08-19 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0024_exam_profile_activities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='curriculum.academicclass', verbose_name='class')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='curriculum.learningarea', verbose_name='subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'class subject allocation',
                'verbose_name_plural': 'class subject allocations',
                'ordering': ['academic_class__academic_level__order', 'academic_class__order', 'learning_area__display_order', 'learning_area__name'],
                'constraints': [models.UniqueConstraint(fields=('academic_class', 'learning_area'), name='unique_teacher_allocation_per_class_and_subject')],
            },
        ),
    ]
