# Generated by Django 6.1 on 2026-08-19 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0025_class_subject_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLearningTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_levels', models.ManyToManyField(related_name='generated_learning_timetables', to='curriculum.academiclevel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_learning_timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'generated learning timetable',
                'verbose_name_plural': 'generated learning timetables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedLearningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=3)),
                ('period_name', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_lessons', to='curriculum.academicclass')),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_lessons', to='curriculum.academiclevel')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_lessons', to='curriculum.learningarea')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_lessons', to=settings.AUTH_USER_MODEL)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.generatedlearningtimetable')),
            ],
            options={
                'verbose_name': 'generated learning lesson',
                'verbose_name_plural': 'generated learning lessons',
                'ordering': ['academic_level__order', 'academic_class__order', 'weekday', 'start_time'],
            },
        ),
    ]
