# Generated by Django 6.1 on 2026-08-19 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0026_generated_learning_timetable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='academic year')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, verbose_name='current academic year')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'academic year',
                'verbose_name_plural': 'academic years',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_levels', models.ManyToManyField(related_name='generated_exam_timetables', to='curriculum.academiclevel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_exam_timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'generated exam timetable',
                'verbose_name_plural': 'generated exam timetables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedExamSitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=3)),
                ('period_name', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exam_sittings', to='curriculum.academicclass')),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exam_sittings', to='curriculum.academiclevel')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exam_sittings', to='curriculum.learningarea')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exam_sittings', to=settings.AUTH_USER_MODEL)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sittings', to='curriculum.generatedexamtimetable')),
            ],
            options={
                'verbose_name': 'generated exam sitting',
                'verbose_name_plural': 'generated exam sittings',
                'ordering': ['academic_level__order', 'academic_class__order', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='term name')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('opening_date', models.DateField(verbose_name='opening date')),
                ('midterm_date', models.DateField(verbose_name='midterm date')),
                ('closing_date', models.DateField(verbose_name='closing date')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='term order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='curriculum.academicyear', verbose_name='academic year')),
            ],
            options={
                'verbose_name': 'academic term',
                'verbose_name_plural': 'academic terms',
                'ordering': ['academic_year', 'order', 'start_date', 'name'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_term_name_per_academic_year')],
            },
        ),
        migrations.CreateModel(
            name='ExamSupervisorAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_supervisor_allocations', to='curriculum.academicclass', verbose_name='class')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_supervisor_allocations', to='curriculum.learningarea', verbose_name='subject')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_supervisor_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'exam supervisor allocation',
                'verbose_name_plural': 'exam supervisor allocations',
                'ordering': ['academic_class__academic_level__order', 'academic_class__order', 'learning_area__display_order', 'learning_area__name'],
                'constraints': [models.UniqueConstraint(fields=('academic_class', 'learning_area'), name='unique_supervisor_allocation_per_class_and_subject')],
            },
        ),
    ]
