# Generated by Django 6.1 on 2026-08-19 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0027_exam_supervisor_allocation_and_generated_timetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedexamsitting',
            options={'ordering': ['academic_level__order', 'academic_class__order', 'exam_date', 'weekday', 'start_time'], 'verbose_name': 'generated exam sitting', 'verbose_name_plural': 'generated exam sittings'},
        ),
        migrations.AddField(
            model_name='generatedexamsitting',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedexamtimetable',
            name='academic_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_exam_timetables', to='curriculum.academicterm'),
        ),
        migrations.AddField(
            model_name='generatedexamtimetable',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_exam_timetables', to='curriculum.academicyear'),
        ),
        migrations.AddField(
            model_name='generatedexamtimetable',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedexamtimetable',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
