# Generated by Django 6.1 on 2026-08-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0031_cbc_lesson_plan_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedexamtimetable',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='exam name'),
        ),
    ]
