# Generated by Django 6.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0032_generated_exam_timetable_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academicclass",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "TEACHER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_classes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="class teacher",
            ),
        ),
    ]
