# Generated by Django 6.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_student_is_suspended"),
        ("curriculum", "0033_academicclass_class_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassAttendanceSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attendance_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_attendance_sessions",
                        to="curriculum.academicclass",
                        verbose_name="class",
                    ),
                ),
                (
                    "taken_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_attendance_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "class attendance session",
                "verbose_name_plural": "class attendance sessions",
                "ordering": ["-attendance_date", "-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("academic_class", "attendance_date"),
                        name="unique_class_attendance_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClassAttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("morning", models.BooleanField("morning session", default=False)),
                ("afternoon", models.BooleanField("afternoon session", default=False)),
                ("evening", models.BooleanField("evening session", default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="curriculum.classattendancesession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_attendance_records",
                        to="admissions.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "class attendance record",
                "verbose_name_plural": "class attendance records",
                "ordering": ["student__last_name", "student__first_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "student"),
                        name="unique_class_attendance_per_student",
                    )
                ],
            },
        ),
    ]
