# Generated by Django 6.1 on 2026-08-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0034_class_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='current academic term'),
        ),
    ]
