# Generated by Django 6.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0035_academicterm_is_current"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ELearningSubjectAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elearning_subject_allocations",
                        to="curriculum.academiclevel",
                        verbose_name="academic level",
                    ),
                ),
                (
                    "learning_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elearning_allocations",
                        to="curriculum.learningarea",
                        verbose_name="subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "TEACHER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elearning_subject_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "e-learning subject allocation",
                "verbose_name_plural": "e-learning subject allocations",
                "ordering": [
                    "academic_level__order",
                    "learning_area__display_order",
                    "learning_area__name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("academic_level", "learning_area"),
                        name="unique_elearning_teacher_per_level_and_subject",
                    )
                ],
            },
        ),
    ]
