# Generated by Django 6.1 on 2026-08-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0036_elearning_subject_allocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningscheduleprofile',
            options={'ordering': ['kind', 'category', 'name'], 'verbose_name': 'learning schedule profile', 'verbose_name_plural': 'learning schedule profiles'},
        ),
        migrations.RemoveConstraint(
            model_name='learningscheduleprofile',
            name='unique_learning_schedule_profile_per_category',
        ),
        migrations.AddField(
            model_name='learningscheduleprofile',
            name='kind',
            field=models.CharField(choices=[('learning', 'Learning'), ('elearning', 'E-learning')], db_index=True, default='learning', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='learningscheduleprofile',
            constraint=models.UniqueConstraint(fields=('kind', 'name', 'category'), name='unique_learning_schedule_profile_per_kind_and_category'),
        ),
    ]
