# Generated by Django 6.1 on 2026-08-21 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_student_profile_image'),
        ('curriculum', '0038_generated_elearning_timetable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ELearningAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='curriculum.elearningsubjectallocation')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elearning_attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'e-learning attendance session',
                'verbose_name_plural': 'e-learning attendance sessions',
                'ordering': ['-lesson_date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ELearningAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elearning_attendance_records', to='admissions.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='curriculum.elearningattendancesession')),
            ],
            options={
                'verbose_name': 'e-learning attendance record',
                'verbose_name_plural': 'e-learning attendance records',
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ELearningSubjectLessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(blank=True, max_length=255)),
                ('substrand', models.CharField(blank=True, max_length=255)),
                ('lesson_learning_outcomes', models.TextField(blank=True, verbose_name='lesson learning outcomes')),
                ('key_inquiry_questions', models.TextField(blank=True, verbose_name='key inquiry questions')),
                ('core_competencies', models.TextField(blank=True, verbose_name='core competencies')),
                ('values', models.TextField(blank=True)),
                ('pcis', models.TextField(blank=True, verbose_name='PCIs')),
                ('learning_resources', models.TextField(blank=True, verbose_name='learning resources')),
                ('organization_of_learning', models.TextField(blank=True, verbose_name='organization of learning')),
                ('introduction', models.TextField(blank=True)),
                ('lesson_development', models.TextField(blank=True, verbose_name='lesson development')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan', to='curriculum.elearningsubjectallocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elearning_lesson_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'e-learning subject lesson plan',
                'verbose_name_plural': 'e-learning subject lesson plans',
            },
        ),
        migrations.CreateModel(
            name='ELearningSubjectOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.TextField(blank=True, verbose_name='e-learning subject outcome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject_outcome', to='curriculum.elearningsubjectallocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_elearning_subject_outcomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'e-learning subject outcome',
                'verbose_name_plural': 'e-learning subject outcomes',
            },
        ),
        migrations.AddConstraint(
            model_name='elearningattendancesession',
            constraint=models.UniqueConstraint(fields=('allocation', 'lesson_date'), name='unique_elearning_attendance_per_day'),
        ),
        migrations.AddConstraint(
            model_name='elearningattendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_elearning_attendance_per_student'),
        ),
    ]
