# Generated by Django 6.1 on 2026-08-21 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_student_profile_image'),
        ('curriculum', '0039_elearning_attendance_lesson_plan_outcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ELearningAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elearning_assessments', to='curriculum.academicterm')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elearning_assessments', to='curriculum.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elearning_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'e-learning assessment',
                'verbose_name_plural': 'e-learning assessments',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ELearningLearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_format', models.CharField(choices=[('NOTES', 'Notes/handouts (PDF)'), ('LECTURE_VIDEO', 'Lecture video (MP4)'), ('SLIDES', 'Slides (PDF or PPTX)'), ('QUIZ_SCORM', 'Quizzes/interactive (SCORM package)'), ('AUDIO', 'Audio (MP3)')], max_length=20, verbose_name='material format')),
                ('category', models.CharField(max_length=120, verbose_name='category')),
                ('name', models.CharField(max_length=200, verbose_name='material name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cover_image', models.ImageField(blank=True, upload_to='elearning/materials/covers/%Y/%m/', verbose_name='cover image')),
                ('material_file', models.FileField(upload_to='elearning/materials/files/%Y/%m/', verbose_name='material file')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_extension', models.CharField(blank=True, max_length=12)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('is_published', models.BooleanField(default=True, help_text='Published materials appear for download in student and parent portals.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_materials', to='curriculum.elearningsubjectallocation', verbose_name='e-learning subject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_elearning_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'e-learning learning material',
                'verbose_name_plural': 'e-learning learning materials',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ELearningAssessmentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='curriculum.elearningassessment')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elearning_assessment_marks', to='curriculum.learningarea', verbose_name='subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elearning_assessment_marks', to='admissions.student')),
            ],
            options={
                'verbose_name': 'e-learning assessment mark',
                'verbose_name_plural': 'e-learning assessment marks',
                'ordering': ['student__last_name', 'student__first_name', 'learning_area__display_order'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'student', 'learning_area'), name='unique_elearning_mark_per_student_and_subject')],
            },
        ),
    ]
