# Generated by Django 6.1 on 2026-08-25 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0040_elearning_assessment_marks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'assigned_roles__role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_classes', to=settings.AUTH_USER_MODEL, verbose_name='class teacher'),
        ),
        migrations.AlterField(
            model_name='classsubjectallocation',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'assigned_roles__role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='elearningsubjectallocation',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'assigned_roles__role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='elearning_subject_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examsupervisorallocation',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'assigned_roles__role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_supervisor_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generatedelearninglesson',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'assigned_roles__role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='generated_elearning_lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
