# Generated by Django 6.1 on 2026-08-25 07:48

from django.db import migrations, models


def backfill_mark_out_of(apps, schema_editor):
    ExamMark = apps.get_model("curriculum", "ExamMark")
    ELearningAssessmentMark = apps.get_model("curriculum", "ELearningAssessmentMark")
    ExamSubjectSetting = apps.get_model("curriculum", "ExamSubjectSetting")
    LearningArea = apps.get_model("curriculum", "LearningArea")

    settings_out_of = {
        (level_id, area_id): out_of
        for level_id, area_id, out_of in ExamSubjectSetting.objects.values_list(
            "academic_level_id", "learning_area_id", "out_of_marks"
        )
    }
    area_totals = dict(LearningArea.objects.values_list("id", "total_marks"))

    exam_updates = []
    for mark in ExamMark.objects.filter(out_of_marks__isnull=True).prefetch_related(
        "generation__academic_levels"
    ).iterator(chunk_size=500):
        out_of = None
        for level in mark.generation.academic_levels.all():
            candidate = settings_out_of.get((level.id, mark.learning_area_id))
            if candidate is not None:
                out_of = candidate
                break
        if out_of is None:
            out_of = area_totals.get(mark.learning_area_id, 100)
        mark.out_of_marks = out_of
        exam_updates.append(mark)
        if len(exam_updates) >= 500:
            ExamMark.objects.bulk_update(exam_updates, ["out_of_marks"])
            exam_updates = []
    if exam_updates:
        ExamMark.objects.bulk_update(exam_updates, ["out_of_marks"])

    elearning_updates = []
    for mark in ELearningAssessmentMark.objects.filter(out_of_marks__isnull=True).select_related(
        "student"
    ).iterator(chunk_size=500):
        # E-learning marks use level settings via the student's academic pathway when available;
        # fall back to the learning area total.
        out_of = area_totals.get(mark.learning_area_id, 100)
        mark.out_of_marks = out_of
        elearning_updates.append(mark)
        if len(elearning_updates) >= 500:
            ELearningAssessmentMark.objects.bulk_update(elearning_updates, ["out_of_marks"])
            elearning_updates = []
    if elearning_updates:
        ELearningAssessmentMark.objects.bulk_update(elearning_updates, ["out_of_marks"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0041_employee_multi_role_limit_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="elearningassessmentmark",
            name="out_of_marks",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Out-of value that applied when this mark was saved. Kept until the mark is edited.",
                null=True,
                verbose_name="out of marks",
            ),
        ),
        migrations.AddField(
            model_name="exammark",
            name="out_of_marks",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Out-of value that applied when this mark was saved. Kept until the mark is edited.",
                null=True,
                verbose_name="out of marks",
            ),
        ),
        migrations.RunPython(backfill_mark_out_of, noop_reverse),
    ]
