# Generated by Django 6.1 on 2026-09-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0045_generated_exam_timetable_scheduled_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combinedexamsubject',
            options={'ordering': ['academic_level__order', 'name'], 'verbose_name': 'combined assessment subject', 'verbose_name_plural': 'combined assessment subjects'},
        ),
        migrations.AlterModelOptions(
            name='combinedexamsubjectcomponent',
            options={'ordering': ['position', 'id'], 'verbose_name': 'combined assessment subject component', 'verbose_name_plural': 'combined assessment subject components'},
        ),
        migrations.AlterModelOptions(
            name='exammark',
            options={'ordering': ['student__last_name', 'student__first_name', 'learning_area__display_order'], 'verbose_name': 'assessment mark', 'verbose_name_plural': 'assessment marks'},
        ),
        migrations.AlterModelOptions(
            name='examscheduleactivity',
            options={'ordering': ['start_time', 'order', 'name'], 'verbose_name': 'assessment schedule activity', 'verbose_name_plural': 'assessment schedule activities'},
        ),
        migrations.AlterModelOptions(
            name='examscheduleprofile',
            options={'ordering': ['category', 'name'], 'verbose_name': 'assessment schedule profile', 'verbose_name_plural': 'assessment schedule profiles'},
        ),
        migrations.AlterModelOptions(
            name='examsubjectsetting',
            options={'ordering': ['academic_level__order', 'display_order', 'learning_area__display_order', 'learning_area__name'], 'verbose_name': 'assessment subject setting', 'verbose_name_plural': 'assessment subject settings'},
        ),
        migrations.AlterModelOptions(
            name='examsupervisorallocation',
            options={'ordering': ['academic_class__academic_level__order', 'academic_class__order', 'learning_area__display_order', 'learning_area__name'], 'verbose_name': 'assessment supervisor allocation', 'verbose_name_plural': 'assessment supervisor allocations'},
        ),
        migrations.AlterModelOptions(
            name='examtimetablesession',
            options={'ordering': ['start_time', 'order', 'name'], 'verbose_name': 'assessment timetable session', 'verbose_name_plural': 'assessment timetable sessions'},
        ),
        migrations.AlterModelOptions(
            name='generatedexamsitting',
            options={'ordering': ['academic_level__order', 'academic_class__order', 'exam_date', 'weekday', 'start_time'], 'verbose_name': 'generated assessment sitting', 'verbose_name_plural': 'generated assessment sittings'},
        ),
        migrations.AlterModelOptions(
            name='generatedexamtimetable',
            options={'ordering': ['-created_at'], 'verbose_name': 'generated assessment timetable', 'verbose_name_plural': 'generated assessment timetables'},
        ),
        migrations.AlterField(
            model_name='examscheduleprofile',
            name='exam_session_duration_minutes',
            field=models.PositiveIntegerField(default=120, verbose_name='assessment session duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='examscheduleprofile',
            name='first_exam_start_time',
            field=models.TimeField(verbose_name='first assessment starts at'),
        ),
        migrations.AlterField(
            model_name='examscheduleprofile',
            name='last_exam_end_time',
            field=models.TimeField(verbose_name='assessment end time'),
        ),
        migrations.AlterField(
            model_name='generatedexamtimetable',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='assessment name'),
        ),
    ]
