# Generated by Django 6.1 on 2026-08-16 07:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=200)),
                ('relationship_to_student', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=24, unique=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s-]{7,24}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other')], max_length=10)),
                ('academic_level', models.CharField(choices=[('PRE_PRIMARY_1', 'Pre-Primary 1'), ('PRE_PRIMARY_2', 'Pre-Primary 2'), ('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8'), ('GRADE_9', 'Grade 9'), ('FORM_1', 'Form 1'), ('FORM_2', 'Form 2'), ('FORM_3', 'Form 3'), ('FORM_4', 'Form 4'), ('OTHER', 'Other')], max_length=20)),
                ('assessment_number', models.CharField(max_length=50, unique=True)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('sponsorship_category', models.CharField(choices=[('GOVERNMENT', 'Government sponsored'), ('SELF', 'Self sponsored'), ('BOTH', 'Government and self sponsored')], max_length=20)),
                ('sponsor_details', models.TextField(blank=True)),
                ('home_address', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('special_needs', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('parent_guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='admissions.parentguardian')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
