# Generated by Django 6.1 on 2026-08-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_student_admission_number_and_class_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Suspended students cannot use the student portal.'),
        ),
    ]
