# Generated by Django 6.1 on 2026-08-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_student_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='students/profiles/'),
        ),
    ]
