# Generated by Django 5.0.14 on 2026-09-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_student_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissions_enabled', models.BooleanField(default=True, help_text='When off, new student admissions are blocked.')),
                ('auto_generate_admission_number', models.BooleanField(default=False, help_text='When on, admission numbers are assigned automatically on the admit form.')),
                ('admission_number_next', models.PositiveIntegerField(default=1, help_text='Next admission number to assign when auto-generate is enabled.')),
            ],
            options={
                'verbose_name': 'admission settings',
                'verbose_name_plural': 'admission settings',
            },
        ),
    ]
