# Generated by Django 5.0.14 on 2026-09-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_admissionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsettings',
            name='admission_number_pad_width',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minimum digits for the numeric part. Use 0 for no padding (e.g. 4 → 0001).'),
        ),
        migrations.AddField(
            model_name='admissionsettings',
            name='admission_number_prefix',
            field=models.CharField(blank=True, default='', help_text='Optional text placed before the number, e.g. ADM or 2026/.', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionsettings',
            name='admission_number_next',
            field=models.PositiveIntegerField(default=1, help_text='Numeric part of the next admission number to assign.'),
        ),
    ]
