# Generated by Django 5.0.14 on 2026-10-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_parentguardian_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_level',
            field=models.CharField(choices=[('PRE_PRIMARY_1', 'Pre-Primary 1'), ('PRE_PRIMARY_2', 'Pre-Primary 2'), ('GRADE_1', 'Grade 1'), ('GRADE_2', 'Grade 2'), ('GRADE_3', 'Grade 3'), ('GRADE_4', 'Grade 4'), ('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8'), ('GRADE_9', 'Grade 9'), ('FORM_1', 'Form 1'), ('FORM_2', 'Form 2'), ('FORM_3', 'Form 3'), ('FORM_4', 'Form 4'), ('YEAR_1', 'First Year'), ('YEAR_2', 'Second Year'), ('YEAR_3', 'Third Year'), ('YEAR_4', 'Fourth Year'), ('DIPLOMA_1', 'Diploma Year 1'), ('DIPLOMA_2', 'Diploma Year 2'), ('CERTIFICATE_1', 'Certificate Year 1'), ('CERTIFICATE_2', 'Certificate Year 2'), ('BRIDGING', 'Bridging'), ('SHORT_COURSE', 'Short Course'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
