# Generated by Django 6.1 on 2026-08-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='approval_status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HEAD_OF_INSTITUTION', 'Head of Institution'), ('DEPUTY_HEAD_OF_INSTITUTION', 'Deputy Head of Institution'), ('CURRICULUM_COORDINATOR', 'Curriculum Coordinator'), ('TEACHER', 'Teacher'), ('ACCOUNTANT', 'Accountant'), ('LIBRARIAN', 'Librarian'), ('STORE_MANAGER', 'Store Manager'), ('WARDEN', 'Warden'), ('SECRETARY', 'Secretary'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], default='EMPLOYEE', max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user can log in.'),
        ),
    ]
