# Generated by Django 6.1 on 2026-08-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_approval_status_employee_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HEAD_OF_INSTITUTION', 'Head of Institution'), ('DEPUTY_HEAD_OF_INSTITUTION', 'Deputy Head of Institution'), ('CURRICULUM_COORDINATOR', 'Curriculum Coordinator'), ('TEACHER', 'Teacher'), ('ACCOUNTANT', 'Accountant'), ('LIBRARIAN', 'Librarian'), ('STORE_MANAGER', 'Store Manager'), ('WARDEN', 'Warden'), ('SECRETARY', 'Secretary')], default='EMPLOYEE', max_length=32),
        ),
    ]
