# Generated by Django 6.1 on 2026-08-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_role_it_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=120)),
                ('school_type', models.CharField(choices=[('PRIMARY', 'Primary school'), ('SECONDARY', 'Secondary school'), ('MIXED', 'Mixed primary and secondary'), ('INTERNATIONAL', 'International school'), ('SPECIAL_NEEDS', 'Special needs school')], max_length=20)),
                ('ownership', models.CharField(choices=[('PUBLIC', 'Public / government'), ('PRIVATE', 'Private'), ('FAITH_BASED', 'Faith-based'), ('COMMUNITY', 'Community')], max_length=20)),
                ('moe_code', models.CharField(blank=True, max_length=80, verbose_name='Ministry of Education code')),
                ('nemis_number', models.CharField(blank=True, max_length=80)),
                ('knec_centre_number', models.CharField(blank=True, max_length=80)),
                ('curricula', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'school profile',
                'verbose_name_plural': 'school profile',
            },
        ),
    ]
