# Generated by Django 6.1 on 2026-08-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_schoolprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='academic_year_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='academic_year_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='admissions_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='admissions_phone',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='bank_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='board_or_proprietor_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='boarding_facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='boarding_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='departments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='deputy_and_admin_staff',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='enrollment_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='fee_schedule_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='general_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='grade_levels_offered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='inspection_report',
            field=models.FileField(blank=True, upload_to='school/compliance/'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='main_phone',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='mission_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='motto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='mpesa_paybill',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='mpesa_till_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='physical_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='principal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='registration_certificate',
            field=models.FileField(blank=True, upload_to='school/compliance/'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school_logo',
            field=models.ImageField(blank=True, upload_to='school/branding/'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='social_media_links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='streams_offered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='term_structure',
            field=models.CharField(blank=True, default='THREE_TERM_KENYAN', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='transport_routes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='vision_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
