# Generated by Django 6.1 on 2026-08-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employeerole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MISS', 'Miss'), ('MS', 'Ms.'), ('TR', 'Tr.'), ('DR', 'Dr.'), ('PROF', 'Prof.')], max_length=4),
        ),
    ]
