# Generated by Django 5.0.14 on 2026-09-30 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0048_generatedexamtimetable_is_current'),
        ('employees', '0013_set_employment_number_from_employee_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_school_activities', to=settings.AUTH_USER_MODEL)),
                ('grades', models.ManyToManyField(related_name='school_activities', to='curriculum.academiclevel')),
            ],
            options={
                'verbose_name': 'school activity',
                'verbose_name_plural': 'school activities',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SchoolActivityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('day_description', models.CharField(blank=True, help_text='Short note for what happens on this day when the activity spans multiple days.', max_length=255, verbose_name='day description')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='employees.schoolactivity')),
            ],
            options={
                'verbose_name': 'school activity day',
                'verbose_name_plural': 'school activity days',
                'ordering': ['activity_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='schoolactivityday',
            constraint=models.UniqueConstraint(fields=('activity', 'activity_date'), name='unique_school_activity_day'),
        ),
    ]
