# Generated by Django 5.0.14 on 2026-09-30 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_student_enrollment_clearance'),
        ('employees', '0014_school_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentConductRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviour_type', models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad')], max_length=10)),
                ('description', models.TextField()),
                ('incident_date', models.DateField(verbose_name='date when happened')),
                ('witness', models.CharField(max_length=200)),
                ('consequence_or_reward', models.TextField(help_text='Repercussion for bad behaviour, or reward for good behaviour.', verbose_name='repercussion or reward')),
                ('rating', models.PositiveSmallIntegerField(help_text='Severity (1–5) for bad behaviour, or merit (1–5) for good behaviour.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_conduct_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_records', to='admissions.student')),
            ],
            options={
                'verbose_name': 'student conduct record',
                'verbose_name_plural': 'student conduct records',
                'ordering': ['-incident_date', '-created_at'],
            },
        ),
    ]
