# Generated by Django 5.0.14 on 2026-09-30 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grant_permissions_for_approved_employees(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")
    EmployeeRole = apps.get_model("employees", "EmployeeRole")
    EmployeeActivityPermission = apps.get_model("employees", "EmployeeActivityPermission")
    from apps.employees.permissions import activity_codes_for_role

    approved = Employee.objects.filter(approval_status="APPROVED")
    for employee in approved.iterator():
        roles = list(
            EmployeeRole.objects.filter(employee_id=employee.pk).values_list(
                "role", flat=True
            )
        )
        if not roles and employee.role:
            roles = [employee.role]
        for role in roles:
            for code in activity_codes_for_role(role):
                EmployeeActivityPermission.objects.get_or_create(
                    employee_id=employee.pk,
                    role=role,
                    activity_code=code,
                    defaults={"is_enabled": True},
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0015_student_conduct_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeActivityPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("HEAD_OF_INSTITUTION", "Head of Institution"),
                            (
                                "DEPUTY_HEAD_OF_INSTITUTION",
                                "Deputy Head of Institution",
                            ),
                            ("CURRICULUM_COORDINATOR", "Curriculum Coordinator"),
                            ("TEACHER", "Teacher"),
                            ("ACCOUNTANT", "Accountant"),
                            ("LIBRARIAN", "Librarian"),
                            ("STORE_MANAGER", "Store Manager"),
                            ("WARDEN", "Warden"),
                            ("SECRETARY", "Secretary"),
                            ("IT_SUPPORT", "IT Support"),
                        ],
                        max_length=32,
                    ),
                ),
                ("activity_code", models.CharField(max_length=80)),
                ("is_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "employee activity permission",
                "verbose_name_plural": "employee activity permissions",
                "ordering": ["role", "activity_code"],
            },
        ),
        migrations.AddConstraint(
            model_name="employeeactivitypermission",
            constraint=models.UniqueConstraint(
                fields=("employee", "role", "activity_code"),
                name="unique_employee_role_activity_permission",
            ),
        ),
        migrations.RunPython(grant_permissions_for_approved_employees, noop_reverse),
    ]
