# Generated by Django 5.0.14 on 2026-09-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_employee_activity_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolactivity',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=12),
        ),
    ]
