# Generated by Django 5.0.14 on 2026-10-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_expand_activity_action_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary school'), ('SECONDARY', 'Secondary school'), ('MIXED', 'Mixed primary and secondary'), ('COLLEGE', 'College / tertiary'), ('TVET', 'TVET / technical college'), ('INTERNATIONAL', 'International school'), ('SPECIAL_NEEDS', 'Special needs school')], max_length=20),
        ),
    ]
